---
  copyright_image: "https://licensebuttons.net/l/by-nc/4.0/80x15.png"
  copyright_image_link: "https://creativecommons.org/licenses/by-nc/4.0/"
  copyright_text: "Except where otherwise noted, content on this site is licensed under a Creative Commons Attribution-NonCommercial License. (CC-BY-NC)"
